trigger:
  - master

pr: none

resources:
  repositories:
    - repository: templates
      endpoint: "${{ values.bitbucketServiceConnection }}"
      name: carlosrv125/dso-iac-template
      ref: refs/tags/v0.0.5
      type: bitbucket

variables:
  - group: terraform-sample-global
  - template: ../vars/vars-global.yaml

pool:
  vmImage: "ubuntu-22.04"

stages:
  - stage: DEV
    jobs:
      - job: "TerraformApply"
        variables:
          - template: ../vars/vars-dev.yaml
        steps:
          - template: templates/terraform/ci-cd/ci-cd.yaml@templates
            parameters:
              terraform_version: "$(terraform_version)"
              remote_backend_rg_name: "$(remote_backend_rg_name)"
              remote_backend_storage_account_name: "$(remote_backend_storage_account_name)"
              remote_backend_container_name: "$(remote_backend_container_name)"
              remote_backend_key: "$(remote_backend_key)"
              remote_backend_service_connection: "${{ values.remoteBackendServiceConnection }}"
              azurerm_account_service_connection: "${{ values.azurermAccountServiceConnection }}"
              terraform_var_file_path: "$(terraform_var_file_path)"
              terraform_workspace_name: "$(terraform_workspace_name)"
              terraform_secrets:
                TF_VAR_db_password: $(db_password)
              terraform_token_artifactory: $(artifactory_token)
              terraform_token_cloud: $(terraform_token_cloud)

  - stage: UAT
    jobs:
      - job: "TerraformApply"
        variables:
          - template: ../vars/vars-uat.yaml
        steps:
          - template: templates/terraform/ci-cd/ci-cd.yaml@templates
            parameters:
              terraform_version: "$(terraform_version)"
              remote_backend_rg_name: "$(remote_backend_rg_name)"
              remote_backend_storage_account_name: "$(remote_backend_storage_account_name)"
              remote_backend_container_name: "$(remote_backend_container_name)"
              remote_backend_key: "$(remote_backend_key)"
              remote_backend_service_connection: "${{ values.remoteBackendServiceConnection }}"
              azurerm_account_service_connection: "${{ values.azurermAccountServiceConnection }}"
              terraform_var_file_path: "$(terraform_var_file_path)"
              terraform_workspace_name: "$(terraform_workspace_name)"
              terraform_secrets:
                TF_VAR_db_password: $(db_password)
              terraform_token_artifactory: $(artifactory_token)
              terraform_token_cloud: $(terraform_token_cloud)
